<?php

/**
 * @file
 *
 * Make the login screens better :).
 */

// Make sure that the user is not logged in.
global $user;

if (!$user->uid) {
  // If this site is set to private we want to redirect all anonymous users to the login form.
  if (variable_get('betterlogin_private')) {
    // Because of Drush we only want to block anything not from CLI.
    if (arg(0) !== 'user' && php_sapi_name() !== 'cli') {
      drupal_goto('user/login');
    }
  }
  
  // Make sure that anon users cannot go to just /user but directly to the login form.
  if (arg(0) == 'user' && !arg(1)) {
    drupal_goto('user/login');
  }
}

/**
 * Implementation of hook_form_alter().
 *
 * Autofocus on the username field.
 * Some proper page titles would be nice for a change.. User account is a bit boring..
 */
function betterlogin_form_alter(&$form, &$form_state, $form_id) {
  // Autofocus on the username field.
  if ($form_id == 'user_login' || $form_id == 'user_register_form' || $form_id == 'user_pass') {
    $form['name']['#attributes']['autofocus'] = 'autofocus';
  }

  switch ($form_id) {
    case 'user_login':
      drupal_set_title(t('Login'));
      break;

    case 'user_register_form':
      drupal_set_title(t('Register'));
      
      // The registration form behaves differently...
      $form['account']['name']['#attributes']['autofocus'] = 'autofocus';
      break;

    case 'user_pass':
      drupal_set_title(t('Forgot your password?'));
      break;
  }
}
